- src/pages/home/layouts/layout-main.tsx
- main title undefined when chain not selected
> Fix main title undefined

- src/configs/setup-evm-network.ts
- src/pages/home/hooks/use-table-liquidity-pool.tsx
- fix evm pool id
- fix evm sidechain chain decimal
> Fix evm pool id, chain decimal

- src/pages/home/hooks/use-table-liquidity-pool.tsx
> Add mock list

- README.md
- src/moai-xrp-evm/pages/home/layouts/layout-main.tsx
- src/moai-xrp-ledger/pages/home/layouts/layout-main.tsx
- src/moai-xrp-root/pages/home/layouts/layout-main.tsx
- src/pages/home/layouts/layout-main.tsx
- fix main title to 'Your Universal Gateway to Multi-chain Liquidity'
> [TH-156] Fix main title

- src/components/network-chip/index.tsx
- src/components/tables/columns/column-token.tsx
- src/components/tables/headers/_table-headers.stories.tsx
- src/components/tables/headers/header-normal.tsx
- src/components/tables/headers/index.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/pool/layouts/detail-header.tsx
- src/states/components/table/index.ts
- src/states/components/table/token.ts
- src/types/networks/index.ts
- Pool list table ui 수정
- Assets 칼럼, 컴포넌트 삭제
- network chip 수정
- token list 클릭 시 Composition selected 되도록 추가
- 선택된 token 앞으로 정렬
- toggle off 시 토스트팝업 3초간 노출
- detail page 상단 조금 수정 (chip 수정, swap fee 텍스트 삭제)
https://github.com/TeamHeimdallr/moai-web/assets/29878878/c121df0a-1c66-47a9-a37b-f84c4ed9bb33
> [TH-221] Fix pool list table UI

- src/components/buttons/dropdown/index.tsx
- src/components/gnb/index.tsx
- src/components/network-selection/index.tsx
- src/components/tooltips/base/index.tsx
- src/components/tooltips/comming-soon/index.tsx
- src/pages/home/index.tsx
- src/pages/pool/pages/detail/index.tsx
- tailwind.config.js
- TH-277 : 그리드 수정 (Home, detail 페이지 px 80)
- TH-278 : Cancelled 
- TH-279 : Popup shadow 값 수정 
- TH-280 : gnb 툴팁 텍스트 사이즈 수정, 텍스트 스펠링 수정
- TH-281 : Network selection 드롭다운 수정
https://github.com/TeamHeimdallr/moai-web/assets/29878878/5609fe0f-64f8-48e1-8e57-670f14eb5a14
> [TH-277] Fix some UI

- src/components/graph/graph-semi-donut/index.tsx
- src/hooks/components/use-graph-semi-donut.ts
- src/pages/pool/components/pool-compositions.tsx
- src/pages/pool/hooks/components/graph/use-graph-total-composition.ts
- 그래프 추가된 UI로 수정하였습니다.
- 특이사항 : graph 가 들어가는 canvas를 width, height 가 똑같은 정사각형 크기로 설정해야 원하는 크기의 그래프가 나오는데, 그러면 위아래 빈공간을 많이 잡아먹어서 상위 div에서 margin y 값을 -로 줬습니다. 괜찮을까요?
> [TH-233] Fix pool composition UI

- .github/PULL_REQUEST_TEMPLATE.md
- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/api/api-contract/_evm/pool/get-liquidity-pool-balance.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity.ts
- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/_evm/token/approve.ts
- src/api/api-contract/_evm/token/price.ts
- src/api/api-contract/_xrpl/pool/add-liquidity.ts
- src/api/api-contract/_xrpl/pool/get-liquidity-pool-balance.ts
- src/api/api-contract/_xrpl/pool/withdraw-liquidity.ts
- src/api/api-contract/_xrpl/swap/get-swap-histories.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/api/api-contract/_xrpl/token/approve.ts
- src/api/api-contract/_xrpl/token/price.ts
- src/api/api-contract/pool/add-liquiditiy.ts
- src/api/api-contract/pool/withdraw-liquidity.ts
- src/api/api-contract/token/approve.ts
- src/components/tables/headers/header-normal.tsx
- src/hooks/wallets/use-connected-wallet.ts
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/pool/hooks/components/table/use-table-total-provisions.tsx
- src/pages/swap/components/select-token-from-popup.tsx
- src/pages/swap/components/select-token-to-popup.tsx
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- fix xrpl contract issues
- add lp
- withdraw lp
- swap
expected)
> [TH-287] fix xrpl contract issues

- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/_evm/token/approve.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/api/api-contract/token/approve.ts
- src/pages/swap/components/swap-popup.tsx
- fix xrp approve
- disable swap button when prepare contract write hook has error
expected)
> [TH-287] fix approve, disable swap button when error

- src/components/inputs/checkbox/index.tsx
- src/components/inputs/number/index.tsx
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/pages/add-liquidity/index.tsx
- max button per tokens
- price impact warning checkbox
- warning comment for partially deposit
> [TH-238] Fix add-liquidity UI

- src/abi/futurepass.ts
- src/api/api-contract/_evm/balance/get-token-balance-in-pool.ts
- src/api/api-contract/_evm/pool/fpass-add-liquidity.ts
- src/api/api-contract/_evm/pool/fpass-withdraw-liquidity.ts
- src/api/api-contract/_evm/pool/get-liquidity-pool-balance.ts
- src/api/api-contract/_evm/swap/fpass-swap.ts
- src/api/api-contract/_evm/token/fpass-approve.ts
- src/api/api-contract/pool/add-liquiditiy.ts
- src/api/api-contract/pool/withdraw-liquidity.ts
- src/api/api-contract/swap/swap.ts
- src/api/api-contract/token/approve.ts
- src/hooks/contexts/use-network.ts
- src/hooks/wallets/use-connected-wallet.ts
- futurepass integration for TRN
> Implement futurepass integration

- src/api/api-contract/_evm/pool/get-liquidity-pool-balance.ts
- src/components/tables/table/index.tsx
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/pool-info.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/components/pool-swap-histories.tsx
- src/pages/pool/hooks/components/table/use-table-total-provisions.tsx
- src/pages/pool/layouts/detail-header.tsx
- src/pages/pool/layouts/detail-left.tsx
- table ui 토글로 수정
- title ui 수정
- pool info 수정
> [TH-226,TH-227,TH-235] Fix detail page ui

- src/hooks/wallets/use-connected-wallet.ts
- src/pages/pool/components/user-pool-balances.tsx
- src/pages/swap/components/swap-input-group.tsx
- Use address with corresponding network
> Use address with corresponding network

- src/api/api-contract/_evm/pool/fpass-add-liquidity.ts
- src/api/api-contract/_evm/pool/fpass-withdraw-liquidity.ts
- src/api/api-contract/_evm/swap/fpass-swap.ts
- src/api/api-contract/_evm/token/fpass-approve.ts
- Fix calling `encodeFunctionData` when enabled
> Fix calling `encodeFunctionData` when enabled

- src/api/api-contract/_evm/swap/fpass-swap.ts
- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/_evm/token/fpass-approve.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/api/api-contract/_xrpl/token/approve.ts
- src/api/api-contract/swap/swap.ts
- src/pages/swap/components/swap-popup.tsx
- apply slippage tolerance when swapping
- don't approve for toToken when isEvm is true
> [TH-283] Implement slippage tolerance

- src/api/axios.ts
- src/api/pools/pools-get.ts
- src/constants/constant-env.ts
- src/types/pools/index.ts
- get pool list, detail api 작성했습니다
> [TH-187] Add get pool list/detail api

- .env.example
- .github/workflows/deploy-devnet.yml
- .github/workflows/deploy-landing.yml
- index.html
- src/constants/constant-env.ts
- src/pages/index.tsx
- src/pages/landing/components/contents/index.tsx
- src/pages/landing/components/gnb/index.tsx
- tailwind.config.js
> [TH-306] Fix route config, update deploy scripts

- src/api/api-contract/_xrpl/balance/get-token-balance-in-pool.ts
- src/api/api-contract/_xrpl/pool/get-liquidity-pool-provisions.ts
- src/api/api-contract/_xrpl/swap/get-swap-histories.ts
- src/api/api-contract/_xrpl/token/approve.ts
- src/components/account/account-detail/index.tsx
- src/constants/constant-env.ts
- fix env configs
- fix stale time, approve max value
expected)
> [TH-314] approve max value

- src/api/api-contract/_evm/balance/get-token-balance-in-pool.ts
- src/api/api-contract/_xrpl/balance/get-token-balance-in-pool.ts
- src/api/utils/query-keys.ts
- xrpl chain, evm chain에서 각각 토큰 밸런스를 받아올때 풀에 들어있는 임의의 토큰들을 불러올수 있도록 수정
- swap을 위한 balance 훅은 다시 만들어야함
expected)
> [TH-174] Remove hard code from the getting balance hooks

- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- success popup ui for "add liquidity"
- success popup ui for "withdraw liquidity"
- success popup ui for "swap"
> [TH-319] Implement Success Popup UI

- src/components/tables/columns/column-icon-text.tsx
- src/components/tables/columns/column-link.tsx
- src/components/tables/columns/column-normal.tsx
- src/components/tables/headers/header-normal.tsx
- src/components/tables/headers/header-sortable.tsx
- src/components/tables/table/index.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/layouts/layout-liquidity-pool-my.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/components/pool-swap-histories.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- src/pages/pool/hooks/components/table/use-table-total-composition.tsx
- src/pages/pool/hooks/components/table/use-table-total-provisions.tsx
- 테이블 비율 수정했습니다.
- 테이블에 type Prop 을 pool with chain / pool without chain / provision / swap 으로 주도록 해서 각 테이블에 맞는 비율로 설정했습니다.
> [TH-216] Fix table ratio

- src/api/token/token-get.ts
- Token list, 낱개 정보 가져오는 api 구현하였습니다
- 이름을 getTokens, getToken 으로 하면 헷갈릴 거 같아서 getTokenList, getToken 으로 했습니다.
- pool - liquidity provision, swap history 는 타입 수정 -> 기존 코드 매우 수정 이 있어서 일단 남겨놨습니다. 
> [TH-202] Add get token list/detail api

- src/api/api-contract/_evm/balance/get-token-balance-in-pool.ts
- src/api/api-contract/_evm/swap/fpass-swap.ts
- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/_evm/token/fpass-approve.ts
- src/api/api-contract/_xrpl/balance/get-token-balance-in-pool.ts
- src/api/api-contract/swap/swap.ts
- src/components/network-selection/index.tsx
- src/components/popup/network-alert/index.tsx
- src/pages/pool/pages/add-liquidity/index.tsx
- src/pages/pool/pages/detail/index.tsx
- src/pages/pool/pages/withdraw-liquidity/index.tsx
- src/pages/swap/components/select-token-from-popup.tsx
- src/pages/swap/components/select-token-to-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- src/pages/swap/index.tsx
- swap logic 수정 : totoken 잔액이 없는 경우 오류가 나는것에 대한 수정
- fromtoken은 풀에 있는 토큰들 중 balance가 있는것만, totoken은 밸런스가 없는것도 전부 가져오도록 수정
**- TODO : 지금은 하드 코딩된 풀 하나에 대해서만 작동하는데 나중에 풀이 많아지면 체인위에서 관리하는 토큰 전부와 그에 대한 최적화된 가격이 정해지는 로직으로 수정 필요**
- swap step ui 추가
- approve 로직 개선
- swap tx 링크 수정
**- TODO : 지금은 루트 테스트 네트워크 tx이 explorer에 반영되는 시간이 엄청 느린데 메인넷에서도 그런지 확인 후 필요하면 수정**
> [TH-297, TH-252] Improvement swap logic

- src/api/api-contract/_evm/balance/get-token-balance-in-pool.ts
- src/api/api-contract/_evm/swap/fpass-swap.ts
- src/components/gnb/index.tsx
- src/components/network-selection/index.tsx
- src/components/popup/network-alert/index.tsx
- src/hooks/contexts/use-network.ts
- src/pages/home/index.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/home/layouts/layout-main.tsx
- src/pages/pool/pages/detail/index.tsx
- src/pages/swap/index.tsx
- src/states/components/popup/index.ts
- src/states/data/network/select-network.ts
- 선택된 네트워트에 해당하는 지갑이 연결되어있지 않은 경우 보여지는 배너를 모든 페이지에서 볼 수 있도록 수정
- 네트워크 변경시 경고 팝업을 네트워크선택 드랍다운에서 뿐만 아니라 홈페이지에서 테이블을 선택시에도 볼수 있도록 전역변수를 설정
> Fix banner and popup logic

- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- src/pages/pool/hooks/components/table/use-table-total-provisions.tsx
- src/pages/pool/layouts/detail-header.tsx
- 연결된 네트워크에 따라서 redirect 시키는 url parameter가 조금씩 달라서 알맞게 수정
> [TH-326] Fix the URL according to the connected network

- src/components/token-list/index.tsx
- src/pages/swap/components/select-token-from-popup.tsx
- src/pages/swap/components/select-token-to-popup.tsx
swap select token popup 수정 디자인 반영
> [TH-325] Fix design of the select popup

- src/hooks/wallets/use-futurepass-of.ts
- Add enable option of `futurepassOf`
> Add enable option of `futurepassOf`

- src/hooks/wallets/use-connected-wallet.ts
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-total-provisions.tsx
table에서 my tab을 보여줄때 사용하는 address가 체인별 대응이 안되어 있는 bug 수정
> [TH-333] Fix address that used in table according to pool network

- src/components/account/account/index.tsx
- src/components/gnb/index.tsx
- src/pages/campaign/components/gnb/index.tsx
- src/pages/campaign/components/pending/bridge-history.tsx
- src/pages/campaign/landing/contents/index.tsx
- src/pages/campaign/landing/index.tsx
- src/pages/index.tsx
- 지갑이 하나도 안 연결되어있을때 / 하나라도 연결되어있을때 지갑 띄우는 로직 개선
- 지갑이 fpass-metamask만 연결되었을때 지갑 아이콘 보이는 부분 수정
- usetable 무한 렌더링 부분 수정
> Fix wallet connect

- src/constants/constant-vars.ts
- src/hooks/utils/use-media-query.ts
- src/pages/campaign/components/gnb/index.tsx
- src/pages/campaign/components/pending/bridge-history.tsx
- src/pages/campaign/components/pending/index.tsx
- src/pages/campaign/components/table/table-column-time.tsx
- src/pages/campaign/components/token-card/index.tsx
- src/pages/campaign/components/token-list/index.tsx
- src/pages/campaign/landing/contents/index.tsx
- src/pages/campaign/landing/index.tsx
- src/pages/campaign/layouts/layout-liquidity-pool.tsx
- tailwind.config.js
-반응형 구현
https://github.com/TeamHeimdallr/moai-web/assets/93644826/4ab0424a-6811-4c8e-8f28-bafed15d9bbc
https://github.com/TeamHeimdallr/moai-web/assets/93644826/c9d2452a-aa78-4beb-a47e-2600eb092cbc
> [TH-341] Implement Campaign landing page responsive

- src/components/account/account-detail/index.tsx
- src/components/account/account/index.tsx
- src/components/buttons/dropdown/index.tsx
- src/components/footer/index.tsx
- src/components/gnb/index.tsx
- src/components/menu-mobile/index.tsx
- src/components/network-selection/index.tsx
- src/components/notification/notification/index.tsx
- src/pages/campaign/components/gnb/index.tsx
- 네트워크 셀렉션 메뉴 안으로 이동
- break point 수정
- 푸터 메뉴 안과 밖 디자인 수정
- 그 외 갭, 호버, 셀렉티드 등 디자인 안맞는 버그들 수정
> [Th-382] Fix Gnb responsive

- src/components/connect-wallet/index.tsx
- src/components/graph/graph-semi-donut/index.tsx
- src/components/tables/columns/column-link.tsx
- src/components/tables/table/index.tsx
- src/locales/en/translation.json
- src/locales/i18n.ts
- src/locales/ko/translation.json
- src/pages/campaign/landing/components/pending/bridge-history.tsx
- src/pages/home/layouts/layout-liquidity-pool-my.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/home/layouts/layout-main.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/pool-info.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/components/pool-swap-histories.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/pool/hooks/components/table/use-table-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- src/pages/swap/components/swap-popup.tsx
> [TH-398] Fix i18n omitted config

- src/app.tsx
- src/components/gnb/index.tsx
- src/components/inputs/number/index.tsx
- src/components/popup/index.tsx
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/pages/add-liquidity/index.tsx
- Add liquidity 반응형입니다.
- 팝업 반응형 때문에 조금 시간이 걸렸습니다. 뒤에껀 금방하겠습니다
https://github.com/TeamHeimdallr/moai-web/assets/29878878/e0d96c3c-4405-4cf9-8ab5-b46b74e4b76d
> [TH-393] Add Liquidity Responsive

- src/assets/logos/logo-landing.svg
- src/components/buttons/primary/large-icon-trailing/index.tsx
- src/components/buttons/primary/medium-icon-trailing/_button-primary-medium-icon-trailing.stories.tsx
- src/components/buttons/primary/medium-icon-trailing/index.tsx
- src/components/language-change/index.tsx
- src/constants/constant-vars.ts
- src/hooks/utils/use-media-query.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/landing/components/contents/index.tsx
- src/pages/landing/components/gnb/index.tsx
- tailwind.config.js
> [TH-390] implement landing page responsive

- src/components/alerts/banner/index.tsx
- src/components/buttons/chip/filter/index.tsx
- src/components/buttons/dropdown/index.tsx
- src/components/gnb/index.tsx
- src/components/network-chip/index.tsx
- src/components/network-selection/index.tsx
- src/components/tables/columns/column-token.tsx
- src/components/tables/table-mobile/index.tsx
- src/components/tables/table/index.tsx
- src/components/token/index.tsx
- src/hooks/components/use-banner.ts
- src/pages/campaign/landing/contents/index.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/index.tsx
- src/pages/home/layouts/layout-liquidity-pool-my.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/home/layouts/layout-main.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/components/pool-swap-histories.tsx
- src/pages/pool/pages/add-liquidity/index.tsx
- src/pages/pool/pages/detail/index.tsx
- src/pages/pool/pages/withdraw-liquidity/index.tsx
- src/pages/swap/index.tsx
- implement main page responsive view
expected)
> [TH-391] implement main page responsive

- src/components/tab/index.tsx
- src/components/token-list/index.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
- src/pages/pool/pages/withdraw-liquidity/index.tsx
- src/utils/util-pools.ts
- Withdraw reponsive
- Tab scroll
- TODO : tab scroll shadow on both side
> [TH-394] Add withdraw responsive

- src/locales/en/translation.json
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- src/pages/swap/index.tsx
- Swap responsive
- 수정사항이 별로 없습니다.
> [TH-395] Add swap responsive

- src/components/buttons/primary/medium/index.tsx
- src/components/menu-mobile/index.tsx
- src/components/tab/index.tsx
- src/components/tables/columns/column-token-pair.tsx
- src/components/tables/columns/column-token-swap.tsx
- src/components/tables/table-mobile/index.tsx
- src/hooks/components/use-banner.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/layouts/layout-liquidity-pool-my.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/pool/components/pool-compositions-chart.tsx
- src/pages/pool/components/pool-compositions-label.tsx
- src/pages/pool/components/pool-compositions.tsx
- src/pages/pool/components/pool-header.tsx
- src/pages/pool/components/pool-info-chart.tsx
- src/pages/pool/components/pool-info.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/components/pool-swap-histories.tsx
- src/pages/pool/components/user-pool-balances.tsx
- src/pages/pool/hooks/components/table/use-table-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- src/pages/pool/pages/detail/index.tsx
> [TH-392] implement detail responsive

- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/substrate/send-extrinsic-with-signature.ts
- src/api/api-contract/_evm/swap/substrate-swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
- src/api/api-contract/pool/add-liquiditiy.ts
- src/api/api-contract/pool/withdraw-liquidity.ts
- src/api/api-contract/swap/swap.ts
- src/api/api-contract/token/approve.ts
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- src/pages/swap/components/swap-popup.tsx
- substrate call of swap
- substrate call of add liquidity
- substrate call of withdraw liquidity
- substrate call of approve
> Implement substrate call instead of contract call

- src/api/api-contract/_evm/pool/add-liquidity-fpass.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-fpass.ts
- src/api/api-contract/_evm/swap/fpass-swap.ts
- src/api/api-contract/_evm/token/approve-fpass.ts
- src/components/tab/index.tsx
- src/pages/pool/hooks/components/table/use-table-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- feat: outlinks and disable contract fpass
> feat: outlinks and disable contract fpass

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/user-pool-balances.tsx
> hotfix: wallet balance

- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/hooks/contexts/use-handle-input.ts
> [TH-415] fix xrpl add liquidity input issue

- src/components/footer/index.tsx
- src/states/data/network/select-network.ts
- Link discord, docs link
- Make trn to default network
expected)
> [TH-407] fix sns link, make root to default network

- src/components/gnb/index.tsx
- src/components/popup/index.tsx
- src/hooks/components/use-banner.ts
- src/hooks/wallets/use-connect-evm-wallet.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- fix injected wallet persist
- add switch network modal and banner
expected)
> [TH-388] fix network persist, switch network modal and banner

- src/locales/en/translation.json
- src/locales/ko/translation.json
- handle singular express, ex: "minute ago" 
expected)
> [TH-434] implmenet date singular

- src/pages/pool/hooks/components/table/use-table-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- Value is fixed at the price at the time the action occurred
expected)
> [TH-435] fix history value

- index.html
- src/api/api-contract/_evm/balance/user-all-token-balances.ts
- src/api/api-contract/_evm/balance/user-pool-token-balances.ts
- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/calculate-add-liquidity.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
- src/api/api-contract/_evm/token/approve.ts
- src/api/api-contract/swap/swap.ts
- src/api/api-server/sor/batch-swap.ts
- src/components/account/slippage/index.tsx
- src/constants/constant-network.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/pool-info-chart.tsx
- src/pages/pool/components/pool-info.tsx
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- src/types/pools/index.ts
- src/utils/util-token.ts
- integrate server sor api
- fix all issues in swap and swap result
expected)
> [TH-477] integrate sor, fix all issues to batch swap in futurepass

- src/components/account/account-detail/index.tsx
- user has no futurepass wallet, redirect to create page in mainnet
- in devnet create internally
expected)
> [TH-432] implement fpass redirect in mainnet

- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/user-pool-balances.tsx
- Deposit disable temporary
expected)
> Deposit disable temporary

- src/components/inputs/number/index.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/utils/util-pools.ts
- decimal point floor
expected)
> Fix withdraw max value

- .github/workflows/deploy-mainnet2.yml
- src/constants/constant-env.ts
- add script
- fix api endpoint
expected)
> [TH-462] add another mainnet deploy config

- .github/workflows/deploy-mainnet2.yml
- src/constants/constant-env.ts
> [TH-462] fix minor depoly configs

- .github/workflows/deploy-mainnet2.yml
- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/components/gnb/index.tsx
- src/constants/constant-env.ts
- src/constants/constant-vars.ts
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/user-pool-balances.tsx
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- disable add, swap logic in mainnet1 for redeploy pool
expected)
> [TH-466] temporary stop add lp, swap

- src/api/api-contract/_evm/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/token/lp-token-supply.ts
- src/api/api-server/pools/get-my-pools.ts
- src/hooks/utils/index.ts
- src/hooks/utils/use-previous.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/layouts/layout-main.tsx
- src/types/pools/index.ts
- change api spec, get to post
expected)
> [TH-464] fix my liquidity api

- src/configs/evm-network.ts
- src/hooks/components/use-banner.ts
- src/hooks/wallets/use-add-network.ts
implement the root network add and switch network
expected)
> [TH-463] implement add network

- src/constants/constant-network.ts
- fix vault contract address
expected)
> [TH-469] fix vault address

- src/api/api-contract/_evm/balance/user-pool-token-balances.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
- src/api/api-contract/_evm/token/approve.ts
- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/api/api-contract/token/approve.ts
- src/components/inputs/number/index.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- src/utils/util-pools.ts
- Fix Number type's precision problem by using bigint
- for LP tokens
> Fix Number type's precision problem by using bigint

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
- src/pages/swap/components/swap-input-group.tsx
- fix swap, add lp, withdraw lp error message when pool balance impact too high
expected)
> [TH-470] balancer pool error message

- src/components/footer/index.tsx
> [TH-472] fix discord invite link

- src/components/tab/index.tsx
- src/components/tables/columns/column-token.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/pool/components/pool-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-liquidity-provisions.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- fix table sorting issues
expected)
> [TH-474] fix table issues

- src/pages/pool/components/pool-info.tsx
- format number of trading fee
> Fix: format number of fee

- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- fix step logic for approve
expected)
> [TH-475] fix add lp approve logic

- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/swap/substrate-swap.ts
- src/api/api-contract/_evm/token/approve-fpass.ts
- src/api/api-contract/_evm/token/approve.ts
- src/pages/swap/components/select-token-from-popup.tsx
- src/pages/swap/components/select-token-to-popup.tsx
- src/pages/swap/components/swap-input-group.tsx
> Fix recent select token UI

- src/pages/pool/hooks/contexts/use-handle-input.ts
> fix: handle optimize typo

- src/components/inputs/number/index.tsx
> [TH-484] fix decimal issues

- src/api/api-contract/swap/swap.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/home/layouts/layout-main.tsx
- src/pages/swap/components/swap-input-group.tsx
- feat: disable slippage tolerance termporaily
> feat: disable slippage tolerance termporaily

- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/swap/substrate-swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- src/states/contexts/network-fee-error/network-fee-error.ts
- implement network fee error
- fix approve max
expected)
> [TH-482] fix approve max, handle network fee error

- src/constants/constant-vars.ts
- src/pages/index.tsx
> fix: reward page disable

- .github/workflows/deploy-mainnet2.yml
- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/components/inputs/number/index.tsx
- src/constants/constant-env.ts
- src/constants/constant-network.ts
- src/constants/constant-vars.ts
- src/pages/index.tsx
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/user-pool-balances.tsx
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
> [TH-485] optimize pub client

- src/api/api-contract/swap/swap.ts
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
> feat: enable slippage

- src/api/api-contract/_evm/substrate/filter-extrinsic-events.ts
- src/api/api-contract/_evm/substrate/format-event-data.ts
- src/api/api-contract/_evm/substrate/send-extrinsic-with-signature.ts
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- feat: swap result with actual swap result
> feat: swap result with actual swap result

- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- change output value
expected)
> Fix query batch swap handler minor issues

- src/api/api-contract/_evm/substrate/send-extrinsic-with-signature.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- feat: evm success or fail case
> feat: evm success or fail case

- src/components/token-list/index.tsx
- src/pages/campaign/step/components/add-liquidity/index.tsx
- src/pages/campaign/step/components/stepper/index.tsx
- src/pages/campaign/step/components/title/index.tsx
- src/pages/campaign/step/index.tsx
> [TH-345] Add campaign step page responsive

- src/components/inputs/number/index.tsx
> Rollback debounce

- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
- src/api/api-contract/_evm/token/approve.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/api/api-contract/_xrpl/token/approve.ts
- src/pages/swap/components/swap-popup.tsx
- feat: gas estimation of swap and approve
> feat: gas estimation of swap and approve

- src/locales/en/translation.json
- src/locales/i18n.ts
- src/locales/ko/translation.json
- src/pages/campaign/components/gnb/index.tsx
- src/pages/campaign/components/tooltip/enough-xrp/index.tsx
- src/pages/campaign/landing/components/pending/index.tsx
- src/pages/campaign/landing/components/token-list/index.tsx
- src/pages/campaign/landing/contents/index.tsx
- src/pages/campaign/landing/description/section1.tsx
- src/pages/campaign/landing/description/section2.tsx
- src/pages/campaign/layouts/layout-my-voyage.tsx
- src/pages/campaign/step/components/add-liquidity/index.tsx
- src/pages/campaign/step/components/bridge/index.tsx
- src/pages/campaign/step/components/title/index.tsx
- 캠페인 한글화 완료입니다.
- i18n.ts 에서 lng:'ko' 로 설정 후 step 페이지 한글화 확인 가능
> [TH-369] Add campaign i18n

- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity.ts
- src/api/api-contract/_xrpl/pool/add-liquidity.ts
- src/api/api-contract/_xrpl/pool/withdraw-liquidity.ts
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- Implement gas estimation of LP-related
> Implement gas estimation of LP-related

- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/substrate/filter-extrinsic-events.ts
- src/components/inputs/number/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- handle evm error case
expected)
> [TH-492] implement failed popup

- src/api/api-server/rewards/get-reward-list.ts
> Fix negative value

- src/pages/landing/components/contents/index.tsx
- src/pages/landing/components/gnb/index.tsx
- src/pages/landing/index.tsx
- 메인 랜딩 페이지 UI 수정입니다.
https://github.com/TeamHeimdallr/moai-web/assets/29878878/87dafca0-408f-403a-89c1-9dbfbae0ebe5
https://github.com/TeamHeimdallr/moai-web/assets/29878878/07409ca0-02ed-416e-96fb-a6e9e2b4c530
> [TH-497] Fix main landing UI

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/landing/components/pending/index.tsx
- src/pages/campaign/landing/index.tsx
- src/pages/campaign/layouts/layout-my-voyage.tsx
- src/pages/index.tsx
- 캠페인 랜딩 페이지 UI 수정사항 반영입니다.
- My voyage 수정
- 펜딩 컴포넌트 수정
> [TH-386] Fix campaign landing UI

- src/api/api-contract/_xrpl/bridge/bridge-xrpl-to-root.ts
- src/components/skeleton/list-skeleton.tsx
- src/constants/constant-env.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/components/tooltip/address/index.tsx
- src/pages/campaign/step/components/bridge/index.tsx
- src/pages/campaign/step/components/move-step/index.tsx
- src/pages/index.tsx
> [TH-518] implement xrpl-root native bridge

- src/components/loadings/step/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/home/layouts/layout-main-campaign.tsx
- src/pages/pool/components/pool-info.tsx
> [TH-529] fix count down ui

- src/pages/campaign/pages/participate/components/step-buttons.tsx
- src/pages/campaign/pages/participate/hooks/use-step.ts
- src/pages/campaign/pages/participate/index.tsx
- src/pages/campaign/pages/participate/layouts/layout-step3-bridge.tsx
> [TH-530] Activate step4 ui

- src/components/skeleton/table-mobile-skeleton.tsx
- src/components/skeleton/table-skeleton.tsx
- src/components/tables/table-mobile/index.tsx
- src/components/tables/table/index.tsx
- src/main.tsx
- src/pages/home/layouts/layout-liquidity-pool-my.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/home/layouts/layout-main.tsx
- 홈페이지 스켈레톤입니다.
- 기존 Table 컴포넌트에 skeleton height props 를 추가하였습니다.
- my balance 추가입니다.
https://github.com/TeamHeimdallr/moai-web/assets/29878878/237d179f-7f12-40be-a7ed-f3cd0b9d72cd
https://github.com/TeamHeimdallr/moai-web/assets/29878878/8c6465c2-3e16-4299-b6ec-1e7eece5766a
> [TH-261] Add Home skeleton

- src/components/skeleton/skeleton-base.tsx
- src/pages/pool/index.tsx
- src/pages/pool/pages/detail/detail-skeleton.tsx
> [TH-262] Add pool detail skeleton

- src/pages/rewards/index.tsx
> [TH-541] Add Reward skeleton

- src/hooks/wallets/use-connectors.ts
- src/pages/campaign/pages/landing/components/pending.tsx
- src/pages/campaign/pages/landing/layouts/layout-main.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/campaign/pages/participate/hooks/use-step.ts
- src/pages/campaign/pages/participate/layouts/layout-step3-bridge.tsx
- src/pages/campaign/pages/participate/states/step.ts
> [TH-533] implement pending component

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/pool-info-chart.tsx
> [TH-547] fix tvl value in chart

- src/abi/campaign.ts
- src/constants/constant-network.ts
- update campaign abi and address
> feat: updated campaign abi and address

- src/hocs/hoc-react-query-provider.tsx
- src/pages/pool/components/pool-info-chart.tsx
- src/pages/pool/pages/detail/detail-skeleton.tsx
> [Th-547] fix tvl minor issues, disable suspense

- src/abi/campaign.ts
- src/constants/constant-network.ts
- Add new campaign contract (withdraw event)
> Add new campaign contract (withdraw event)

- src/api/api-contract/_evm/campaign/lp-balance.ts
- src/api/api-contract/_evm/campaign/user-campaign-info.ts.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/components/token-list.tsx
- src/pages/campaign/pages/landing/layouts/layout-main.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/home/layouts/layout-main.tsx
- src/types/rewards/index.ts
- connect veMOI, root reward api in campaign page
- connect tvl, apr api in campaign page
expected)
> [TH-534] connect campaign main api

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/pool/components/potential-risks.tsx
- src/pages/pool/pages/detail/index.tsx
> [TH-549] implement potential risk component to pool detail page

- src/api/api-contract/_evm/campaign/withdraw-liquidity-substrate.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/components/withdraw-liquidity-popup.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- Implement campaign withdraw w/ FP
- Remain time
> [TH-548] Implement campaign withdraw w/ FP

- src/api/api-contract/_evm/campaign/add-liquidity-substrate.ts
- src/api/api-contract/_evm/campaign/claim-substrate.ts
- src/api/api-contract/_evm/campaign/claim.ts
- src/hooks/wallets/use-connectors.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/components/token-list-vertical.tsx
- src/pages/campaign/pages/landing/index.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
- src/pages/index.tsx
- src/states/contexts/network-fee-error/network-fee-error.ts
> [TH-550] connect claim contract

- src/api/api-contract/_evm/token/approve.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
> [TH-551] add gas fee alert, lock up accept checkbox when add lp in campaign

- src/pages/index.tsx
> Activate campaign route in devnet

- src/pages/campaign/index.tsx
- src/pages/home/layouts/layout-main.tsx
- src/types/campaign/index.ts
> [TH-552] apply campaign route and campaign main active condition

- src/hooks/wallets/use-futurepass-of.ts
> Add auto change fpass to evm when fpass doesnt have

- src/api/api-contract/_evm/campaign/add-liquidity.ts
- src/api/api-contract/_evm/campaign/claim-substrate.ts
- src/api/api-contract/_evm/campaign/claim.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity.ts
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/campaign/pages/participate/hooks/use-step.ts
- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
- src/pages/campaign/pages/participate/states/step.ts
> [TH-556] campaign minor issues

- src/pages/campaign/components/gnb.tsx
- src/pages/campaign/pages/landing/components/withdraw-liquidity-popup.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/campaign/pages/participate/hooks/use-step.ts
- src/pages/campaign/pages/participate/index.tsx
- src/pages/campaign/pages/participate/layouts/layout-step3-bridge.tsx
> [TH-556] fix campaign minor issues

- src/pages/campaign/components/connect-wallet-popup.tsx
> feat: connect wallet align

- src/components/tooltips/comming-soon/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/home/layouts/layout-main-campaign.tsx
> Fix campaign page minor

- src/locales/en/translation.json
> Fix wrong typo in campaign component

- src/pages/campaign/pages/landing/components/token-list-vertical.tsx
- src/pages/campaign/pages/landing/components/withdraw-liquidity-popup.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/campaign-tool.tsx
- src/pages/pool/pages/detail/index.tsx
> [TH-557] pool detail campaign

- src/api/api-contract/_evm/token/approve-substrate.ts
- src/api/api-contract/_evm/token/approve.ts
> Fix allowance min

- src/components/account/account/index.tsx
- src/hooks/wallets/use-connected-wallet.ts
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/campaign-tool.tsx
> [TH-558] fix wallet gem default selected, campaign empty condition

- src/api/api-contract/_evm/campaign/lp-balance.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/layouts/layout-main.tsx
> [TH-559] fix campaign tvl

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/components/pending.tsx
- src/pages/campaign/pages/landing/layouts/layout-partner.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
> [TH-560] fix futureverse partnership ui, fix i18n

- src/locales/en/translation.json
> [TH-560] fix the

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/index.tsx
- src/pages/maintenance/index.tsx
> [TH-572] implement maintenance, set reward to maintenance

- src/pages/campaign/pages/landing/components/token-list-vertical.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/campaign-tool.tsx
> [TH-572] fix veMOI for maintenance

- src/pages/campaign/pages/landing/layouts/layout-main.tsx
> [TH-581] fix campaign main tvl to protocol tvl

- src/hocs/hoc-web3-provider.tsx
> [TH-582] implement connect to coinbase in wallet connect

- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
> feat: korean button align

- src/components/tooltips/apr/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/participate/index.tsx
> Fix margin, moai token name

- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
- fix: fee estimation after approval
> fix: fee estimation after approval

- src/components/footer/index.tsx
- src/pages/campaign/pages/landing/layouts/layout-disclaimer.tsx
> Fix discord invitation link

- src/hooks/wallets/use-futurepass-of.ts
> [TH-583] fix auto changing to evm logic

- src/hooks/analaystics/ga-wallet-identity.tsx
> fix identity when user connect fpass

- src/components/network-selection/index.tsx
- src/hooks/wallets/use-connected-wallet.ts
- src/locales/ko/translation.json
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/campaign-tool.tsx
- src/pages/pool/components/pool-header.tsx
- src/pages/pool/components/pool-info-chart.tsx
- src/pages/pool/pages/detail/index.tsx
> [TH-602] fix xrpl minor issues

- src/api/api-contract/_evm/campaign/lp-balance.ts
- src/api/api-contract/_evm/campaign/user-campaign-info.ts.ts
> Fix campaign apr

- src/api/api-contract/_evm/campaign/lp-balance.ts
- src/api/api-contract/_evm/campaign/user-campaign-info.ts.ts
> Fix moi apr of campaign

- src/api/api-contract/_evm/campaign/user-campaign-info.ts.ts
- src/api/api-server/pools/get-charts.ts
- src/api/api-server/pools/get-my-pools.ts
- src/api/api-server/pools/get-pool.ts
- src/api/api-server/pools/get-pools.ts
> Fix doubled volume error

- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- Fix doubled volume error of swap history
> Fix doubled volume error of swap history

- src/pages/swap/components/swap-popup.tsx
> [TH-602] fix minor issues in xrpl

- src/api/api-server/maintanence/get-maintanence.ts
- src/hooks/utils/use-maintanence.tsx
- src/pages/campaign/index.tsx
- src/pages/index.tsx
- src/pages/pool/index.tsx
- src/types/index.ts
- src/types/maintanence/index.ts
> [TH-570] implement maintanence api

- .github/workflows/deploy-mainnet-th.yml
> [TH-603] fix scripts

- src/api/api-server/pools/get-pool.ts
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/campaign-tool.tsx
> [TH-603] remove - string

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/rewards/hooks/components/use-table-rewards.tsx
- Rename reward table's LP volume label
> Rename reward table's LP volume label

- src/api/api-contract/_evm/campaign/lp-balance.ts
- src/api/api-contract/_evm/campaign/user-campaign-info.ts.ts
- src/api/api-server/pools/get-my-pools.ts
- src/api/api-server/pools/get-pool.ts
- src/api/api-server/pools/get-pools.ts
- src/components/tooltips/apr/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/layouts/layout-main.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
- src/pages/pool/components/campaign-tool.tsx
- src/pages/pool/components/pool-info.tsx
- src/pages/rewards/components/reward-info.tsx
- src/pages/rewards/hooks/components/use-table-rewards.tsx
- src/types/pools/index.ts
> [TH-612] fix moi to moai

- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/api/api-contract/_xrpl/pool/calculate-withdraw-liquidity.ts
- src/api/api-contract/_xrpl/token/lp-token-supply.ts
> [TH-619] update amm_info request

- src/api/api-server/faucet/post-faucet-xrpl.ts
- src/constants/constant-network.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/faucet/components/faucet-list.tsx
- src/pages/faucet/components/faucet-token-card.tsx
- src/pages/faucet/index.tsx
- src/pages/index.tsx
- src/types/pools/index.ts
- Implement faucet token for XRPL Devnet
---
> [TH-614] Implement faucet token for XRPL Devnet

- src/components/gnb/index.tsx
- src/components/menu-mobile/index.tsx
- src/constants/constant-vars.ts
- src/pages/faucet/index.tsx
- src/pages/rewards/index.tsx
- src/types/components/index.ts
> [TH-620] change gnb, navigation adjust to current network

- src/components/tooltips/apr/index.tsx
- src/pages/faucet/components/faucet-list.tsx
- src/pages/pool/components/pool-info.tsx
- Fix hard-coded trading fee
- Remove MOAI pre-mining APR of XRPL
- Sort faucet token lists
> Edit trading fee and apr of XRPL

- src/hooks/wallets/use-connected-wallet.ts
> Fix xaman forced network

- src/api/api-contract/_evm/balance/user-all-token-balances.ts
- src/api/api-contract/_evm/balance/user-pool-token-balances.ts
- src/api/api-contract/_evm/pool/calculate-add-liquidity.ts
- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/api/api-contract/_xrpl/pool/add-liquidity.ts
- src/api/api-contract/_xrpl/pool/calculate-add-liquidity.ts
- src/api/api-contract/_xrpl/token/lp-token-supply.ts
- src/api/api-contract/pool/add-liquiditiy.ts
- src/api/api-contract/pool/calculate-add-liquidity.ts
- src/api/api-server/pools/get-my-pools.ts
- src/api/api-server/pools/get-pool.ts
- src/api/api-server/pools/get-pools.ts
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/hooks/contexts/use-handle-input.ts
- src/types/pools/index.ts
> [TH-622] xrpl single deposit

- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/pool/hooks/contexts/use-handle-input.ts
- src/states/components/input-group/token.ts
> Fix xrpl single deposit ui issues

- src/pages/pool/components/add-liquidity-popup.tsx
> Fix xrpl lp token trust line issues

- src/constants/constant-vars.ts
- src/pages/index.tsx
> Remove xrpl faucet in mainnet

- src/constants/constant-vars.ts
- src/pages/index.tsx
> Fix xrpl faucet show condition

- src/api/api-contract/_evm/swap/batch-swap.ts
- src/api/api-contract/swap/swap.ts
- src/pages/swap/components/swap-input-group.tsx
- Enable batchswap for EVM Sidechain devnet
> Enable batchswap for EVM Sidechain devnet

- src/api/api-server/faucet/post-faucet-evm-sidechain.ts
- src/constants/constant-network.ts
- src/constants/constant-vars.ts
- src/hooks/utils/use-maintanence.tsx
- src/pages/faucet/components/faucet-list.tsx
- src/pages/faucet/components/faucet-token-card-evm-sidechain.tsx
- src/pages/faucet/components/faucet-token-card-xrpl.tsx
- src/pages/faucet/index.tsx
- src/types/pools/index.ts
> [TH-638] implement evm sidechain faucet

- src/pages/faucet/components/faucet-token-card-evm-sidechain.tsx
- src/pages/faucet/components/faucet-token-card-xrpl.tsx
> [TH-639] implement adding token to mm in faucet page

- src/assets/icons/icon-dot.svg
- src/assets/icons/index.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/lending/data/index.ts
- src/pages/lending/pages/detail/components/asset-borrow-info-chart.tsx
- src/pages/lending/pages/detail/components/asset-borrow-info.tsx
- src/pages/lending/pages/detail/components/asset-interest-rate-model.tsx
- src/pages/lending/pages/detail/components/asset-supply-info-chart.tsx
- src/pages/lending/pages/detail/components/asset-supply-info.tsx
- src/pages/lending/pages/detail/index.tsx
- src/pages/pool/components/pool-info-chart.tsx
- src/types/charts/index.ts
> [TH-629] implement interest rate model

- src/api/api-contract/_evm/campaign/withdraw-liquidity-substrate.ts
> Fix fpass gas limit in campaign withdraw

- src/api/api-contract/lending/borrow.ts
- src/components/inputs/number/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/lending/pages/borrow/components/borrow-popup.tsx
- src/pages/lending/pages/borrow/index.tsx
- src/pages/lending/pages/detail/components/user-asset-info.tsx
- src/pages/lending/pages/supply/components/supply-input-group.tsx
- src/states/contexts/network-fee-error/network-fee-error.ts
> [TH-634] implement lending borrow input, popup ui

- src/api/api-contract/lending/withdraw.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-popup.tsx
- src/pages/lending/pages/withdraw/index.tsx
- src/states/contexts/network-fee-error/network-fee-error.ts
> [TH-633] implement lending withdrawal input, popup ui

- src/api/api-server/lending/get-charts-apy.ts
- src/api/api-server/lending/get-charts-irate-model.ts
- src/configs/analystics.ts
- src/pages/lending/pages/detail/components/asset-borrow-info-chart.tsx
- src/pages/lending/pages/detail/components/asset-interest-rate-model.tsx
- src/pages/lending/pages/detail/components/asset-supply-info-chart.tsx
- src/types/lending/index.ts
> [TH-644] connecting lending apy, interest rate model chart api

- src/abi/moai-lens.ts
- src/api/api-contract/_evm/lending/borrow.ts
- src/api/api-contract/_evm/lending/enter-exit-market.ts
- src/api/api-contract/_evm/lending/get-assets-in.ts
- src/api/api-contract/_evm/lending/repay.ts
- src/api/api-contract/_evm/lending/underlying-price.ts
- src/api/api-contract/_evm/lending/user-account-snapshot-all.ts
- src/api/api-contract/_evm/lending/user-account-snapshot.ts
- src/api/api-contract/_evm/lending/user-available-borrow.ts
- src/api/api-contract/lending/borrow.ts
- src/api/api-contract/lending/enter-exit-market.ts
- src/api/api-contract/lending/get-markets-in.ts
- src/api/api-contract/lending/repay.ts
- src/constants/constant-network.ts
- src/pages/lending/hooks/table/use-table-my-borrows.tsx
- src/pages/lending/hooks/table/use-table-my-supplies.tsx
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/lending/pages/borrow/components/borrow-popup.tsx
- src/pages/lending/pages/borrow/index.tsx
- src/pages/lending/pages/detail/components/asset-info.tsx
- src/pages/lending/pages/main/components/popup-collateral.tsx
- src/pages/lending/pages/main/layouts/layout-market-supplies.tsx
- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/repay/components/repay-popup.tsx
- src/pages/lending/pages/repay/index.tsx
- src/states/contexts/network-fee-error/network-fee-error.ts
- src/types/lending/index.ts
- src/utils/util-lending.ts
- Implement contract call (borrow, supply, enter/exit market, lens, ...)
> Implement contract call (borrow, supply, enter/exit market, lens, ...)

- src/api/api-contract/_evm/lending/get-all-markets.ts
- src/api/api-contract/_evm/lending/get-max-borrow-power.ts
- src/api/api-contract/_evm/lending/mtoken-balances-all.ts
- src/pages/lending/hooks/table/use-table-assets-to-borrow.tsx
- src/pages/lending/hooks/table/use-table-assets-to-suppy.tsx
- src/pages/lending/pages/detail/components/asset-interest-rate-model.tsx
- src/pages/lending/pages/main/layouts/layout-market-info.tsx
- src/utils/util-lending.ts
- Implement tables when wallet is not connected
> Implement tables when wallet is not connected

- src/pages/rewards/components/reward-my-info-waveN.tsx
- src/pages/rewards/index.tsx
> Fix reward vemoai ui

- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/lending/hooks/table/use-table-assets-to-borrow.tsx
- src/pages/lending/hooks/table/use-table-assets-to-suppy.tsx
- src/pages/lending/pages/main/layouts/layout-market-borrows.tsx
- src/pages/lending/pages/main/layouts/layout-market-info.tsx
- src/pages/lending/pages/main/layouts/layout-market-supplies.tsx
- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/repay/components/repay-popup.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- connect wallet button text
- show hf and ltv only if supplies > 0
- token approve before repay
- withdraw only possible when liquidity is enough
> Fix QA Issues

- src/api/api-contract/_evm/lending/get-all-markets.ts
- src/api/api-contract/_evm/lending/get-market.ts
- src/api/api-contract/_evm/lending/get-max-borrow-power.ts
- src/api/api-contract/_evm/lending/user-available-borrow-all.ts
- src/api/api-contract/_evm/lending/user-available-borrow.ts
- src/pages/lending/pages/main/index.tsx
- src/pages/lending/pages/main/layouts/layout-market-borrows.tsx
- src/pages/lending/pages/main/layouts/layout-market-info.tsx
- src/pages/lending/pages/main/layouts/layout-market-supplies.tsx
- src/types/lending/index.ts
- src/utils/util-lending.ts
- Lending QA - market info layout, borrow power, prices, etc
> Lending QA - market info layout, borrow power, prices, etc

- src/api/api-contract/_evm/lending/redeem-underlying-substrate.ts
- src/api/api-contract/_evm/lending/redeem-underlying.ts
- src/api/api-contract/lending/redeem-underlying.ts
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-popup.tsx
- src/utils/util-lending.ts
- QA) withdrawing (redeem) all tokens, use same format of LTV
> QA) withdrawing (redeem) all tokens, use same format of LTV

- src/pages/lending/hooks/table/use-table-assets-to-borrow.tsx
- Disable borrow button when it is not available
> Disable borrow button when it is not available

- src/pages/lending/hooks/table/use-table-my-borrows.tsx
- src/pages/lending/hooks/table/use-table-my-supplies.tsx
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/lending/pages/borrow/components/borrow-popup.tsx
- src/pages/lending/pages/main/components/market-info-current-ltv-popup.tsx
- src/pages/lending/pages/main/components/market-info-health-factor-popup.tsx
- src/pages/lending/pages/main/layouts/layout-market-borrows.tsx
- src/pages/lending/pages/main/layouts/layout-market-info.tsx
- src/pages/lending/pages/main/layouts/layout-market-supplies.tsx
- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/repay/components/repay-popup.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-popup.tsx
- src/pages/lending/pages/withdraw/index.tsx
> [TH-656] fix lending qa ui and style issues

- src/api/api-contract/_evm/balance/user-token-balances.ts
- src/api/api-contract/_evm/substrate/create-futurepass.ts
- src/components/account/futurepass-create-popup/index.tsx
- src/components/tables/columns/column-toggle.tsx
- src/components/toggle/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/lending/hooks/table/use-table-my-supplies.tsx
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/lending/pages/borrow/components/borrow-popup.tsx
- src/pages/lending/pages/main/components/popup-collateral.tsx
- src/pages/lending/pages/main/layouts/layout-market-info.tsx
- src/pages/lending/pages/main/layouts/layout-market-supplies.tsx
- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/repay/components/repay-popup.tsx
- src/pages/lending/pages/supply/components/supply-input-group.tsx
- src/pages/lending/pages/supply/components/supply-popup.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-popup.tsx
> [TH-657] add prepare hooks to lending tx

- src/components/toggle/index.tsx
> [TH-656] fix toggle disabled circle position

- src/api/api-contract/_evm/campaign/add-liquidity-substrate.ts
- src/api/api-contract/_evm/campaign/claim-substrate.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/lending/borrow-substrate.ts
- src/api/api-contract/_evm/lending/enter-exit-market-substrate.ts
- src/api/api-contract/_evm/lending/redeem-underlying-substrate.ts
- src/api/api-contract/_evm/lending/repay-substrate.ts
- src/api/api-contract/_evm/lending/supply-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
> [TH-656] fix gas limit in substrate

- src/pages/lending/hooks/table/use-table-assets-to-borrow.tsx
- src/pages/lending/hooks/table/use-table-my-borrows.tsx
- src/pages/lending/hooks/table/use-table-my-supplies.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- Disable withdraw and borrow if HF <= 1.0
> Disable withdraw and borrow if HF <= 1.0

- src/api/api-contract/_evm/lending/user-available-borrow-all.ts
- src/api/api-contract/_evm/lending/user-available-borrow.ts
- src/pages/lending/hooks/table/use-table-assets-to-borrow.tsx
- src/pages/lending/pages/detail/components/asset-info.tsx
- Fix lending available liquidity
> Fix lending available liquidity

- src/components/buttons/primary/small/index.tsx
- src/components/inputs/number/index.tsx
- src/pages/campaign/pages/landing/layouts/layout-main.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/types/rewards/index.ts
> Fix text for campaign reward

- src/hooks/utils/use-maintanence.tsx
> Fix maintanance

- src/pages/index.tsx
> Fix local flag

- src/hooks/utils/use-maintanence.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/rewards/components/reward-my-info-waveN.tsx
- src/pages/rewards/components/reward-referral.tsx
> Fix lending qa minor

- src/pages/lending/pages/borrow/components/borrow-popup.tsx
- src/pages/lending/pages/main/components/popup-collateral.tsx
- src/pages/lending/pages/repay/components/repay-popup.tsx
- src/pages/lending/pages/supply/components/supply-popup.tsx
- src/pages/lending/pages/withdraw/components/withdraw-popup.tsx
> Fix lending gas loading

- src/components/toggle/index.tsx
- src/pages/lending/hooks/table/use-table-my-supplies.tsx
- Disable collateral toggle if hf <= 1
> Disable collateral toggle if hf <= 1

- src/pages/lending/pages/detail/components/asset-borrow-info-chart.tsx
- src/pages/lending/pages/detail/components/asset-supply-info-chart.tsx
> Fix minor typo

- src/pages/pool/components/pool-info.tsx
- Remove moai apr and use moai points
> Remove moai apr and use moai points

- src/api/api-server/pools/get-my-pools.ts
> Fix my apr of LP

- src/api/api-contract/_evm/campaign/add-liquidity-substrate.ts
- src/api/api-contract/_evm/campaign/claim-substrate.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/lending/borrow-substrate.ts
- src/api/api-contract/_evm/lending/enter-exit-market-substrate.ts
- src/api/api-contract/_evm/lending/redeem-underlying-substrate.ts
- src/api/api-contract/_evm/lending/repay-substrate.ts
- src/api/api-contract/_evm/lending/supply-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
> Use gas estimation

- src/api/api-contract/_evm/lending/get-hypothetical-Account.ts
- src/pages/lending/pages/main/components/popup-collateral.tsx
- Implement hypothetical account liquidity
> Implement hypothetical account liquidity

- src/pages/lending/pages/detail/components/asset-borrow-info.tsx
- src/pages/lending/pages/detail/components/asset-supply-borrow-info-card.tsx
- src/pages/lending/pages/detail/components/asset-supply-info.tsx
- Add usd value of total supplied and borrowed tokens
> Add usd value of total supplied and borrowed tokens

- src/api/api-contract/_evm/lending/get-all-markets.ts
- src/api/api-contract/_evm/lending/get-hypothetical-account.ts
- src/api/api-contract/_evm/lending/get-interest-rate-model.ts
- src/api/api-contract/_evm/lending/get-market.ts
- src/api/api-contract/_evm/lending/get-markets.ts
- src/api/api-contract/_evm/lending/get-max-borrow-power.ts
- src/api/api-contract/_evm/lending/mtoken-balances-all.ts
- src/api/api-contract/_evm/lending/mtoken-metadata.ts
- src/api/api-contract/_evm/lending/underlying-price.ts
- src/api/api-contract/_evm/lending/user-account-liquidity.ts
- src/api/api-contract/_evm/lending/user-account-snapshot-all.ts
- src/api/api-contract/_evm/lending/user-account-snapshot.ts
- src/api/api-contract/_evm/lending/user-available-borrow-all.ts
- src/api/api-contract/_evm/lending/user-available-borrow.ts
- src/pages/lending/hooks/table/use-table-assets-to-borrow.tsx
- src/pages/lending/hooks/table/use-table-my-borrows.tsx
- src/pages/lending/hooks/table/use-table-my-supplies.tsx
- src/pages/lending/pages/main/components/popup-collateral.tsx
- src/utils/util-lending.ts
> [TH-666] add lending nullish colascing

- src/pages/lending/pages/main/components/popup-collateral.tsx
> Fix disable colateral logic

- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/campaign-tool.tsx
> [TH-667] remove moai point temporary

- src/api/api-contract/token/approve.ts
- src/pages/campaign/pages/landing/components/withdraw-liquidity-popup.tsx
> Fix campaign withdarw validation logic

- src/components/token-list-moai-point/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/campaign/pages/landing/components/token-list-vertical.tsx
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/pool/components/campaign-tool.tsx
> [TH-668] fix campaign reward panel to showing point also

- src/api/api-contract/_xrpl/pool/add-liquidity.ts
- src/api/api-contract/_xrpl/pool/withdraw-liquidity.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/pages/pool/components/pool-compositions-chart.tsx
- src/pages/pool/components/pool-compositions.tsx
- src/pages/pool/components/pool-info-chart.tsx
- src/pages/swap/components/select-token-to-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- src/pages/swap/index.tsx
> [TH-673] pool detail chart order

- src/pages/bridge/components/bridge-input-group.tsx
- src/pages/bridge/components/bridge-popup.tsx
> Fix bridge destination address when network is xrpl

- src/pages/bridge/components/bridge-input-group.tsx
- src/pages/bridge/components/bridge-popup.tsx
- src/pages/bridge/hooks/use-balance.ts
> Enable fpass when xrpl to root bridge

- src/pages/pool/pages/detail/index.tsx
> LP Farming start time

- src/api/api-contract/_evm/swap/substrate-swap.ts
- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/swap/swap.ts
- src/api/api-server/sor/batch-swap.ts
- src/api/api-server/sor/get-swap-fallback.ts
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- src/utils/util-token.ts
> [TH-675] implement single swap when direct swap pool path exist

- src/api/api-contract/_evm/balance/user-all-token-balances.ts
- src/api/api-contract/_evm/balance/user-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-token-balances.ts
> [TH-676] modify get token apis the number of taking

- src/configs/evm-network.ts
- src/hocs/hoc-web3-provider.tsx
> [TH-678] implement porcini rpc custom node

- src/abi/composable-stable-pool.ts
- src/api/api-contract/_evm/balance/user-pool-token-balances.ts
- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/api/api-contract/_evm/pool/calculate-add-liquidity.ts
- src/api/api-contract/_evm/pool/calculate-withdraw-liquidity.ts
- src/api/api-contract/_evm/pool/get-actual-supply-stable.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity.ts
- src/api/api-contract/_evm/token/lp-token-supply.ts
- src/api/api-contract/pool/calculate-add-liquidity.ts
- src/constants/constant-network.ts
- src/pages/pool/components/add-liquidity-input-group.tsx
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- src/utils/index.ts
- src/utils/util-stable-pools.ts
- src/utils/util-token.ts
- Implement composable stable pool's functions
> Implement composable stable pool's functions

- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- src/utils/util-stable-pools.ts
- Fix: caculate stable out - zero case
> Fix: caculate stable out - zero case

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
- src/api/api-contract/_evm/balance/user-pool-token-balances.ts
- src/api/api-contract/_evm/token/lp-token-supply.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/pool/components/lp-farm-tool.tsx
- src/pages/pool/components/pool-info.tsx
> [TH-691] farming minor issues

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
> [TH-691] farming minor issues2

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
> [TH-691] fix filter lp token name

- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
> [Th-691] fix null handle

- src/api/api-contract/_evm/balance/user-xrp-balances.tsx
- src/api/api-contract/_xrpl/balance/user-xrp-balances.ts
- src/api/api-contract/balance/user-xrp-balances.ts
- src/pages/campaign/pages/landing/components/bridge-to-xrpl-popup.tsx
- src/pages/campaign/pages/landing/components/withdraw-liquidity-popup.tsx
- src/pages/campaign/pages/participate/layouts/layout-step3-bridge.tsx
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/lending/pages/main/components/popup-collateral.tsx
- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/campaign-tool.tsx
- src/pages/pool/components/lp-farm-popup.tsx
- src/pages/pool/components/lp-unfarm-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
> Add user xrp token balance hook, replace all token balance to xrp token balance fetch

- index.html
> Fix twitter og card type

- index.html
> Fix twitter og

- src/pages/rewards/components/reward-my-info-waveN.tsx
- src/pages/rewards/components/reward-referral.tsx
- src/pages/rewards/hooks/components/use-table-rewards-waveN.tsx
- src/pages/rewards/layouts/layout-waveN.tsx
> [TH-682] fix current wave info

- src/pages/swap/components/select-token-from-popup-xrpl.tsx
- src/pages/swap/components/select-token-from-popup.tsx
- src/pages/swap/components/select-token-popup-xrpl.tsx
- src/pages/swap/components/select-token-to-popup-xrpl.tsx
- src/pages/swap/components/select-token-to-popup.tsx
- src/pages/swap/components/swap-input-group-xrpl.tsx
- src/pages/swap/components/swap-input-group.tsx
> [TH-704] remove token price props in swap popup

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
- src/api/api-contract/_evm/balance/user-all-token-balances.ts
- src/api/api-contract/balance/user-all-token-balances.ts
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/swap/components/swap-input-group.tsx
- update contract reads function to exclude lp token balance so that reducing RPC call
expected)
> [TH-708] update contract reads function to exclude lp token balance

- src/api/api-contract/balance/user-all-token-balances.ts
- set inlcudeLpToken props default value to true
expected)
> [TH-708] add inlcudeLpToken props default value

- src/abi/campaign-reward.ts
- src/api/api-contract/_evm/campaign/claim-substrate.ts
- src/api/api-contract/_evm/campaign/claim.ts
- src/api/api-contract/_evm/campaign/reward-claim-substrate.ts
- src/api/api-contract/_evm/campaign/reward-claim.ts
- src/api/api-contract/_evm/campaign/user-campaign-info.ts.ts
- src/constants/constant-network.ts
- src/pages/campaign/pages/landing/layouts/layout-voyage.tsx
- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
- src/pages/pool/components/campaign-tool.tsx
- Connect campaign reward claim contract
- [x\ New feature (non-breaking change which adds functionality)
> Connect campaign reward claim contract

- src/pages/lending/pages/borrow/components/borrow-popup.tsx
- src/pages/lending/pages/main/components/popup-collateral.tsx
- src/pages/lending/pages/repay/components/repay-popup.tsx
- src/pages/lending/pages/supply/components/supply-popup.tsx
- src/pages/lending/pages/withdraw/components/withdraw-popup.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/swap/components/swap-popup.tsx
- Show fee proxy setting UI if idle status
> Show fee proxy setting UI if idle status

- src/api/api-contract/_evm/campaign/reward-claim-substrate.ts
- src/api/api-contract/_evm/campaign/reward-claim.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity.ts
- Fee estimation with priority x1.5
> Fee estimation with priority x1.5

- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/swap/components/swap-input-group-xrpl.tsx
- src/pages/swap/index.tsx
> [TH-674] fix comments, remove pool add filter token

- src/pages/swap/index.tsx
> [TH-674] fix swap popup to private

- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/components/tables/columns/column-token.tsx
- src/components/token/index.tsx
- src/hooks/wallets/use-connected-wallet.ts
- src/pages/home/components/add-token-xrpl.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/pool/components/add-liquidity-popup.tsx
- src/pages/pool/components/add-liquidity-select-token-popup.tsx
- src/pages/pool/components/pool-header.tsx
- src/pages/pool/components/pool-info.tsx
- src/pages/pool/components/user-pool-balances.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
- src/pages/pool/components/withdraw-liquidity-popup.tsx
- src/pages/pool/pages/add-pool/components/add-liquidity-input-group.tsx
- src/pages/pool/pages/add-pool/components/add-token1-xrpl.tsx
- src/pages/pool/pages/add-pool/components/add-token2-xrpl.tsx
- src/pages/pool/pages/fee-voting/components/voting.tsx
- src/pages/swap/components/add-token-xrpl.tsx
- src/pages/swap/components/swap-popup-xrpl.tsx
- src/pages/swap/components/swap-popup.tsx
> [TH-772] fix amm qa minor issues

- src/configs/evm-network.ts
> fix trn rpc network to public

- src/configs/evm-network.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
> fix devnet network to public

- src/api/api-contract/swap/swap.ts
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
- [TH-714] Choose best swap option between batchswap and swap
> [TH-714] Choose best swap option between batchswap and swap

- src/api/api-contract/_xrpl/amm/amm-create.ts
- src/api/api-contract/_xrpl/amm/amm-vote.ts
- src/api/api-contract/_xrpl/bridge/bridge-xrpl-to-root.ts
- src/api/api-contract/_xrpl/pool/add-liquidity.ts
- src/api/api-contract/_xrpl/pool/withdraw-liquidity.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/api/api-contract/_xrpl/token/approve.ts
> [TH-729] add amm tx source tag 60006000

- src/assets/logos/logo-campaign-1.svg
- src/assets/logos/logo-campaign-2.svg
- src/components/buttons/primary/medium-icon-trailing/index.tsx
- src/pages/home/components/campaign-banner.tsx
- src/pages/home/layouts/layout-liquidity-pool-my.tsx
- src/pages/index.tsx
> [TH-683] implement campaing ended banner, remove page

- src/components/token/index.tsx
- src/pages/pool/components/pool-header.tsx
> [TH-728] fix token rounded

- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-fee-token-balance.ts
- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-xrp-balances.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/swap/components/select-token-from-popup-xrpl.tsx
- src/pages/swap/components/select-token-from-popup.tsx
- src/pages/swap/components/select-token-to-popup-xrpl.tsx
- src/pages/swap/components/select-token-to-popup.tsx
> [TH-729] fix minir xrpl all pool issue, same issuer balance

- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/api/api-contract/_xrpl/balance/user-token-balances.ts
- src/pages/home/components/filter-token-popup-xrpl.tsx
- src/pages/pool/pages/add-pool/components/add-liquidity-input-group.tsx
- src/pages/pool/pages/add-pool/components/add-liquidity-popup.tsx
- src/pages/pool/pages/add-pool/components/select-token1-popup-xrpl.tsx
- src/pages/pool/pages/add-pool/components/select-token2-popup-xrpl.tsx
- src/pages/swap/components/select-token-from-popup-xrpl.tsx
- src/pages/swap/components/select-token-to-popup-xrpl.tsx
> [TH-730] fix xrpl balance when issuer is equal

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
> [TH-729] fix lp farm balance logic

- src/pages/rewards/components/reward-referral-share-popup.tsx
> [TH-731] fix reward share link percent

- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
> Fix query batch swap result

- src/api/api-contract/_xrpl/balance/user-pool-token-balances.ts
- src/pages/pool/components/user-pool-balances.tsx
> [TH-732] handling zero xrp balance

- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/pages/swap/components/swap-input-group.tsx
> [TH-735] fix swap limit mismatch, balancer error#103

- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/swap/swap.ts
- src/pages/swap/components/swap-input-group.tsx
- src/pages/swap/components/swap-popup.tsx
> [TH-735] fix swap balancer issues

- src/api/api-server/events/check-xepe-eligibility.ts
- src/components/inputs/text/index.tsx
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/pages/events/index.tsx
- src/pages/events/pages/xepe/components/gnb.tsx
- src/pages/events/pages/xepe/index.tsx
- src/pages/index.tsx
> [TH-718] implement xepe airdrop page

- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
- src/pages/swap/components/swap-input-group-xrpl.tsx
- src/pages/swap/index.tsx
- src/types/pools/index.ts
> [TH-736] deploy xrpl amm

- src/api/api-contract/_xrpl/amm/amm-create.ts
- src/api/api-contract/_xrpl/balance/user-all-token-balances.ts
- src/api/api-contract/_xrpl/pool/add-liquidity.ts
- src/api/api-contract/_xrpl/pool/withdraw-liquidity.ts
- src/api/api-contract/_xrpl/swap/swap.ts
- src/utils/util-number.ts
> [TH-738] fix xrpl token decimal

- src/api/api-contract/_evm/swap/batch-swap.ts
- Fix batchswap's limits param
> Fix batchswap's limits param

- src/pages/pool/hooks/components/table/use-table-swap-histories.tsx
> Fix mobile swap volume

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
- src/pages/home/hooks/components/table/use-table-liquidity-pool-my.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/pool/components/lp-farm-tool.tsx
- src/pages/pool/components/pool-info.tsx
> Ended status of LP farming

- src/api/api-contract/_evm/balance/lp-farm-balance.ts
- feat: show lp farm deposited amount
> Show lp farm deposited amount

- src/hooks/analaystics/ga-in-view.tsx
- src/hooks/analaystics/ga-page.tsx
- src/hooks/analaystics/ga-route-change.tsx
> Remove pageview, route change amplitude event

- src/pages/rewards/index.tsx
> Fix wave sort

- src/hooks/wallets/use-connect-xrp-wallet.ts
- src/hooks/wallets/use-connected-wallet.ts
> [TH-777] fix crossmark mobile issue

- src/api/api-contract/_evm/lending/user-account-snapshot-all.ts
- src/components/account/account/index.tsx
- src/pages/bridge/components/bridge-popup.tsx
- src/pages/bridge/components/list.tsx
- src/pages/home/hooks/components/table/use-table-liquidity-pool.tsx
- src/pages/home/layouts/layout-liquidity-pool.tsx
- src/pages/rewards/components/reward-my-info-waveN.tsx
- src/pages/swap/components/select-token-from-popup-xrpl.tsx
- src/pages/swap/components/select-token-to-popup-xrpl.tsx
- src/pages/swap/components/swap-input-group-xrpl.tsx
- src/pages/swap/components/swap-popup-xrpl.tsx
- src/utils/util-lending.ts
- src/utils/util-number.ts
> [TH-753] fix decimals, minor issues

- src/pages/lending/pages/detail/components/asset-interest-rate-model.tsx
- Fix interest rate model chart
> Fix interest rate model chart

- src/components/account/account-detail/index.tsx
- src/constants/constant-env.ts
- src/utils/util-string.ts
- Add UID for each connected wallet address
> Add UID for each connected wallet address

- src/components/account/account-detail/index.tsx
> Use full address for UID

- src/pages/lending/pages/detail/components/asset-interest-rate-model.tsx
> Fix utilization rate max

- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- Fix available withdraw amount
> Fix available withdraw amount

- src/components/popup/xumm-qr/index.tsx
- src/hooks/wallets/use-connected-wallet.ts
- src/locales/en/translation.json
- src/locales/ko/translation.json
- src/states/components/xumm-qr/index.ts
> [TH-806] implement mobile xaman qr

- src/pages/campaign/pages/landing/components/withdraw-liquidity-popup.tsx
- src/pages/campaign/pages/participate/layouts/layout-step4-add-liquidity.tsx
- src/pages/lending/pages/borrow/components/borrow-input-group.tsx
- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/supply/components/supply-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
- src/pages/pool/components/withdraw-liquidity-input-group.tsx
-Fix decimal issue of max button
> Fix decimal issue of max button

- src/api/api-contract/_evm/campaign/add-liquidity-substrate.ts
- src/api/api-contract/_evm/campaign/claim-substrate.ts
- src/api/api-contract/_evm/campaign/reward-claim-substrate.ts
- src/api/api-contract/_evm/campaign/reward-claim.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/campaign/withdraw-liquidity.ts
- src/api/api-contract/_evm/lending/borrow-substrate.ts
- src/api/api-contract/_evm/lending/borrow.ts
- src/api/api-contract/_evm/lending/enter-exit-market-substrate.ts
- src/api/api-contract/_evm/lending/enter-exit-market.ts
- src/api/api-contract/_evm/lending/redeem-underlying-substrate.ts
- src/api/api-contract/_evm/lending/redeem-underlying.ts
- src/api/api-contract/_evm/lending/repay-substrate.ts
- src/api/api-contract/_evm/lending/repay.ts
- src/api/api-contract/_evm/lending/supply-substrate.ts
- src/api/api-contract/_evm/lending/supply.ts
- src/api/api-contract/_evm/lp-farm/farm-evm.ts
- src/api/api-contract/_evm/lp-farm/farm-substrate.ts
- src/api/api-contract/_evm/lp-farm/unfarm-evm.ts
- src/api/api-contract/_evm/lp-farm/unfarm-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/add-liquidity.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity-substrate.ts
- src/api/api-contract/_evm/pool/withdraw-liquidity.ts
- src/api/api-contract/_evm/swap/batch-swap.ts
- src/api/api-contract/_evm/swap/substrate-batch-swap.ts
- src/api/api-contract/_evm/swap/substrate-swap.ts
- src/api/api-contract/_evm/swap/swap.ts
- src/api/api-contract/_evm/token/approve-substrate.ts
- src/api/api-contract/_evm/token/approve.ts
update estimate fee accuracnce
expected)
> Update estimate fee

- src/pages/lending/pages/detail/components/asset-interest-rate-model.tsx
> APR to APY on IRM

- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
> Fix sync account snapshot

- src/pages/lending/pages/repay/components/repay-input-group.tsx
- src/pages/lending/pages/withdraw/components/withdraw-input-group.tsx
> withdraw max and repay max
